//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOrdering63131236.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDH
    {
        public int MaDH { get; set; }
        public int MaMA { get; set; }
        public int SoLuong { get; set; }
        public int GiaBan { get; set; }
        public Nullable<int> DanhGia { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
        public virtual MONAN MONAN { get; set; }
    }
}
