//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOrdering63131236.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONHANG()
        {
            this.CHITIETDHs = new HashSet<CHITIETDH>();
        }
    
        public int ID { get; set; }
        public int KhachHang { get; set; }
        public string DcGiaoHang { get; set; }
        public int MaPhuong { get; set; }
        public int MaQuan { get; set; }
        public int MaTP { get; set; }
        public bool XuatHD { get; set; }
        public System.DateTime NgayDatHang { get; set; }
        public Nullable<System.DateTime> NgayGiaoHang { get; set; }
        public Nullable<bool> ThanhCong { get; set; }
        public string DvVanChuyen { get; set; }
        public string MaVanChuyen { get; set; }
        public Nullable<int> PhiShip { get; set; }
        public string GhiChuKhach { get; set; }
        public string GhiChuShop { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDH> CHITIETDHs { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        public virtual PHUONGXA PHUONGXA { get; set; }
        public virtual QUANHUYEN QUANHUYEN { get; set; }
        public virtual TINHTHANH TINHTHANH { get; set; }
    }
}
