//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOrdering63131236.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MONAN()
        {
            this.BINHLUANs = new HashSet<BINHLUAN>();
            this.CHITIETDHs = new HashSet<CHITIETDH>();
            this.ANHs = new HashSet<ANH>();
        }
    
        public int ID { get; set; }
        public int MaLoai { get; set; }
        public string TenMA { get; set; }
        public string TenDuongDan { get; set; }
        public string TomTat { get; set; }
        public System.DateTime NgayDangMA { get; set; }
        public int GiaBan { get; set; }
        public Nullable<int> GiaKM { get; set; }
        public string Dvt { get; set; }
        public int SoLuong { get; set; }
        public int AnhBia { get; set; }
        public string NdMon { get; set; }
        public int LuotXem { get; set; }
        public int LuotMua { get; set; }
        public bool DangMA { get; set; }
    
        public virtual ANH ANH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BINHLUAN> BINHLUANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDH> CHITIETDHs { get; set; }
        public virtual LOAIMON LOAIMON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANH> ANHs { get; set; }
    }
}
